version: "3"
vars:
  IMAGE: '{{.IMAGE | default "ghcr.io/taha2samy/java-8:jdk-std"}}'

includes:
  j8:
    taskfile: ./versions/8/Taskfile.yml
    dir: ./versions/8
tasks:
  test-fips:
    desc: Run all FIPS compliance tests for Java 8
    cmds:
      - task: j8:run-suite
        vars: { IMAGE: "{{.IMAGE}}" }

  test-fips:
    desc: Run all FIPS compliance tests for Java 8
    cmds:
      - task: j8:run-suite
        vars: { IMAGE: "{{.IMAGE}}" }

  update-java:
    cmds:
      - python .github/scripts/update_java.py
    silent: true

  generate-template:
    cmds:
      - python .github/scripts/render_templates.py
    silent: true

  remove_last_runs:
    cmds:
      - |
        gh run list --repo "$GITHUB_REPOSITORY" --limit 1000 --json databaseId -q '.[].databaseId' \
        | xargs -n1 gh run delete --repo "$GITHUB_REPOSITORY"

  generate-readme:
    desc: "Generate README row for a Java version"
    vars:
      V: '{{.V | default "11"}}'
    cmds:
      - |
        python3 .github/scripts/generate_readme.py \
          --metadata 11-bake-metadata.json \
          --template templates/java-version-row.md.j2 \
          --version {{.V}} \
          --output versions/{{.V}}/README_ROW.md
    silent: false

