image_flavors:
  jre-distroless:
    java_type: "jre"
    options:
      has_shell: false
      has_package_manager: false
      use_cache: true
    packages:
      - "glibc"
      - "zlib"
      - "ca-certificates"
      - "wolfi-baselayout"
      - "wolfi-keys"
      - "libgcc"
      - "libstdc++"
      - "tzdata"

  jre-standard:
    java_type: "jre"
    options:
      has_shell: true 
      has_package_manager: true
      use_cache: true
    packages:
      - "apk-tools"
      - "wolfi-keys"
      - "glibc"
      - "zlib"
      - "ca-certificates"
      - "wolfi-baselayout"
      - "wolfi-keys"
      - "libgcc"
      - "libstdc++"
      - "posix-libc-utils"
      - "busybox"
      - "tzdata"

  jdk-standard:
    java_type: "jdk"
    options:
      has_shell: true
      has_package_manager: true
      use_cache: true
    packages:
      - "apk-tools"
      - "wolfi-keys"
      - "glibc"
      - "zlib"
      - "ca-certificates"
      - "wolfi-baselayout"
      - "wolfi-keys"
      - "libgcc"
      - "libstdc++"
      - "posix-libc-utils"
      - "busybox"
      - "bash"
      - "curl"
      - "tzdata"
