# syntax=docker/dockerfile:1.6

FROM {{ wolfi_base }} AS helper
RUN (addgroup -g 1001 java || true) && (adduser -u 1001 -G java -D -s /bin/bash java || true)
RUN mkdir -p /rootfs/etc /rootfs/usr/share/zoneinfo /rootfs/home/java /rootfs/tmp
RUN cp /etc/passwd /rootfs/etc/passwd && \
    cp /etc/group /rootfs/etc/group && \
    echo "hosts: files dns" > /rootfs/etc/nsswitch.conf && \
    echo "UTC" > /rootfs/etc/timezone && \
    chown 1001:1001 /rootfs/home/java && \
    chmod 1777 /rootfs/tmp

FROM {{ wolfi_base }} AS producer
USER root
{{ 'jre_distroless' | setup_flavor(flavors) }}
{{ 'jre_standard' | setup_flavor(flavors) }}
{{ 'jdk_standard' | setup_flavor(flavors) }}

FROM {{ alpine }} AS jdk_fetcher
ARG TARGETARCH
# kics-scan ignore-line
ADD --checksum=sha256:{{ jdk_amd64_sha }} {{ jdk_amd64_url }} /tmp/jdk-amd64.tar.gz
# kics-scan ignore-line
ADD --checksum=sha256:{{ jdk_arm64_sha }} {{ jdk_arm64_url }} /tmp/jdk-arm64.tar.gz
RUN set -eux; apk add --no-cache tar="1.35-r2"; \
    if [ "$TARGETARCH" = "amd64" ]; then SRC="/tmp/jdk-amd64.tar.gz"; else SRC="/tmp/jdk-arm64.tar.gz"; fi; \
    mkdir -p /opt/java-jdk; tar -xzf "$SRC" -C /opt/java-jdk --strip-components=1

FROM {{ alpine }} AS jre_fetcher
ARG TARGETARCH
# kics-scan ignore-line
ADD --checksum=sha256:{{ jre_amd64_sha }} {{ jre_amd64_url }} /tmp/jre-amd64.tar.gz
# kics-scan ignore-line
ADD --checksum=sha256:{{ jre_arm64_sha }} {{ jre_arm64_url }} /tmp/jre-arm64.tar.gz
RUN set -eux; apk add --no-cache tar="1.35-r2"; \
    if [ "$TARGETARCH" = "amd64" ]; then SRC="/tmp/jre-amd64.tar.gz"; else SRC="/tmp/jre-arm64.tar.gz"; fi; \
    mkdir -p /opt/java-jre; tar -xzf "$SRC" -C /opt/java-jre --strip-components=1

FROM {{ wolfi_base }} AS fips-modifier
USER root
RUN apk add --no-cache curl={{ curl }}
ARG KEYSTORE_PWD=changeit
COPY java.security /tmp/java.security
# kics-scan ignore-line
ADD --chmod=644 --checksum=sha256:{{ bouncycastle_fips_sha }} {{ bouncycastle_fips_url }} /tmp/bc-fips.jar
# kics-scan ignore-line
ADD --chmod=644 --checksum=sha256:{{ bouncycastle_util_fips_sha }} {{ bouncycastle_util_fips_url }} /tmp/bcutil-fips.jar
# kics-scan ignore-line
ADD --chmod=644 --checksum=sha256:{{ bouncycastle_tls_fips_sha }} {{ bouncycastle_tls_fips_url }} /tmp/bctls-fips.jar
RUN curl -fLso /tmp/cacert.pem https://curl.se/ca/cacert.pem

COPY --from=jdk_fetcher /opt/java-jdk /opt/jdk
COPY --from=jre_fetcher /opt/java-jre /opt/jre

RUN set -e; \
    for JAVA_PATH in /opt/jdk /opt/jre; do \
        {%- if version == '8' %}
        if [ -d "$JAVA_PATH/jre" ]; then \
            CACERTS="$JAVA_PATH/jre/lib/security/cacerts"; SEC_FILE="$JAVA_PATH/jre/lib/security/java.security"; LIB_DIR="$JAVA_PATH/jre/lib/ext"; \
        else \
            CACERTS="$JAVA_PATH/lib/security/cacerts"; SEC_FILE="$JAVA_PATH/lib/security/java.security"; LIB_DIR="$JAVA_PATH/lib/ext"; \
        fi; \
        {%- else %}
        CACERTS="$JAVA_PATH/lib/security/cacerts"; SEC_FILE="$JAVA_PATH/conf/security/java.security"; LIB_DIR="$JAVA_PATH/lib"; \
        {%- endif %}
        $JAVA_PATH/bin/keytool -importkeystore -srckeystore "$CACERTS" -srcstorepass ${KEYSTORE_PWD} \
        -destkeystore /tmp/cacerts.bcfks -deststoretype BCFKS -deststorepass ${KEYSTORE_PWD} \
        -providerpath "/tmp/bc-fips.jar:/tmp/bcutil-fips.jar" \
        -provider org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider && \
        mv /tmp/cacerts.bcfks "$CACERTS" && mkdir -p "$LIB_DIR" && \
        cp /tmp/bc-fips.jar /tmp/bcutil-fips.jar /tmp/bctls-fips.jar "$LIB_DIR/" && \
        cp /tmp/java.security "$SEC_FILE"; \
    done


FROM scratch AS stage_aggregator_for_jdk
COPY --from=helper /rootfs /
COPY --from=producer /rootfs/jdk_standard /


FROM scratch AS jdk_standard
COPY --from=stage_aggregator_for_jdk /rootfs /
COPY --from=fips-modifier /opt/jdk /opt/java
ENV JAVA_HOME=/opt/java PATH="/opt/java/bin:/usr/local/bin:/usr/bin:/bin"
ARG KEYSTORE_PWD=changeit
{% if version == '8' %}
ENV JAVA_TOOL_OPTIONS="-Dorg.bouncycastle.fips.approved_only=true -Dorg.bouncycastle.jsse.client.assumeExtendedKeyUsage=false -Dorg.bouncycastle.jsse.trustManager.checkEKU=false -Djdk.tls.trustNameService=true -Dkeystore.type=BCFKS -Djavax.net.ssl.trustStore=/opt/java/jre/lib/security/cacerts -Djavax.net.ssl.trustStoreType=BCFKS -Djavax.net.ssl.trustStorePassword=${KEYSTORE_PWD} -Xbootclasspath/a:/opt/java/jre/lib/ext/bc-fips.jar:/opt/java/jre/lib/ext/bcutil-fips.jar:/opt/java/jre/lib/ext/bctls-fips.jar"
{% else %}
ENV JAVA_TOOL_OPTIONS="-Dorg.bouncycastle.fips.approved_only=true -Dorg.bouncycastle.jsse.client.assumeExtendedKeyUsage=false -Dorg.bouncycastle.jsse.trustManager.checkEKU=false -Djdk.tls.trustNameService=true -Dkeystore.type=BCFKS -Djavax.net.ssl.trustStore=/opt/java/lib/security/cacerts -Djavax.net.ssl.trustStoreType=BCFKS -Djavax.net.ssl.trustStorePassword=${KEYSTORE_PWD} -Xbootclasspath/a:/opt/java/lib/bc-fips.jar:/opt/java/lib/bcutil-fips.jar:/opt/java/lib/bctls-fips.jar"
{% endif %}
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD ["/opt/java/bin/jcmd", "-l"]
USER 1001
WORKDIR /home/java
ENTRYPOINT []


FROM scratch AS stage_aggregator_for_jre
COPY --from=helper /rootfs /
COPY --from=producer /rootfs/jre_standard /

FROM scratch AS jre_standard
COPY --from=stage_aggregator_for_jre /rootfs /
COPY --from=fips-modifier /opt/jre /opt/java
ENV JAVA_HOME=/opt/java PATH="/opt/java/bin:/usr/local/bin:/usr/bin:/bin"
ARG KEYSTORE_PWD=changeit
{% if version == '8' %}
ENV JAVA_TOOL_OPTIONS="-Dorg.bouncycastle.fips.approved_only=true -Dorg.bouncycastle.jsse.client.assumeExtendedKeyUsage=false -Dorg.bouncycastle.jsse.trustManager.checkEKU=false -Djdk.tls.trustNameService=true -Dkeystore.type=BCFKS -Djavax.net.ssl.trustStore=/opt/java/lib/security/cacerts -Djavax.net.ssl.trustStoreType=BCFKS -Djavax.net.ssl.trustStorePassword=${KEYSTORE_PWD} -Xbootclasspath/a:/opt/java/jre/lib/ext/bc-fips.jar:/opt/java/jre/lib/ext/bcutil-fips.jar:/opt/java/jre/lib/ext/bctls-fips.jar"
{% else %}
ENV JAVA_TOOL_OPTIONS="-Dorg.bouncycastle.fips.approved_only=true -Dorg.bouncycastle.jsse.client.assumeExtendedKeyUsage=false -Dorg.bouncycastle.jsse.trustManager.checkEKU=false -Djdk.tls.trustNameService=true -Dkeystore.type=BCFKS -Djavax.net.ssl.trustStore=/opt/java/lib/security/cacerts -Djavax.net.ssl.trustStoreType=BCFKS -Djavax.net.ssl.trustStorePassword=${KEYSTORE_PWD} -Xbootclasspath/a:/opt/java/lib/bc-fips.jar:/opt/java/lib/bcutil-fips.jar:/opt/java/lib/bctls-fips.jar"
{% endif %}
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD ["/opt/java/bin/java", "-version"]
USER 1001
WORKDIR /home/java
ENTRYPOINT []

FROM scratch AS stage_aggregator_for_jre
COPY --from=helper /rootfs /
COPY --from=producer /rootfs/jre_distroless /
FROM scratch AS jre_distroless
COPY --from=stage_aggregator_for_jre /rootfs /
COPY --from=fips-modifier /opt/jre /opt/java
ENV JAVA_HOME=/opt/java PATH="/opt/java/bin:/usr/local/bin:/usr/bin:/bin" LANG=C.UTF-8 TZ=UTC
ARG KEYSTORE_PWD=changeit
{% if version == '8' %}
ENV JAVA_TOOL_OPTIONS="-Dorg.bouncycastle.fips.approved_only=true -Dorg.bouncycastle.jsse.client.assumeExtendedKeyUsage=false -Dorg.bouncycastle.jsse.trustManager.checkEKU=false -Djdk.tls.trustNameService=true -Dkeystore.type=BCFKS -Djavax.net.ssl.trustStore=/opt/java/jre/lib/security/cacerts -Djavax.net.ssl.trustStoreType=BCFKS -Djavax.net.ssl.trustStorePassword=${KEYSTORE_PWD} -Xbootclasspath/a:/opt/java/jre/lib/ext/bc-fips.jar:/opt/java/jre/lib/ext/bcutil-fips.jar:/opt/java/jre/lib/ext/bctls-fips.jar"
{% else %}
ENV JAVA_TOOL_OPTIONS="-Dorg.bouncycastle.fips.approved_only=true -Dorg.bouncycastle.jsse.client.assumeExtendedKeyUsage=false -Dorg.bouncycastle.jsse.trustManager.checkEKU=false -Djdk.tls.trustNameService=true -Dkeystore.type=BCFKS -Djavax.net.ssl.trustStore=/opt/java/lib/security/cacerts -Djavax.net.ssl.trustStoreType=BCFKS -Djavax.net.ssl.trustStorePassword=${KEYSTORE_PWD} -Xbootclasspath/a:/opt/java/lib/bc-fips.jar:/opt/java/lib/bcutil-fips.jar:/opt/java/lib/bctls-fips.jar"
{% endif %}
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD ["/opt/java/bin/java", "-version"]
USER 1001
WORKDIR /home/java
ENTRYPOINT ["/opt/java/bin/java"]