name: Build and Push Java Images

on:
  workflow_dispatch:
    inputs:
      java_8:
        type: boolean
        default: true
      java_11:
        type: boolean
        default: true
      java_17:
        type: boolean
        default: true
      java_21:
        type: boolean
        default: true
      java_25:
        type: boolean
        default: true





env:
  repo: java
  ghcr_image: ghcr.io/${{ github.repository_owner }}/java


jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.set-matrix.outputs.versions }}
    steps:
      - id: set-matrix
        run: |
          VERSIONS=()
          [[ "${{ inputs.java_8 }}" == "true" ]] && VERSIONS+=("8")
          [[ "${{ inputs.java_11 }}" == "true" ]] && VERSIONS+=("11")
          [[ "${{ inputs.java_17 }}" == "true" ]] && VERSIONS+=("17")
          [[ "${{ inputs.java_21 }}" == "true" ]] && VERSIONS+=("21")
          [[ "${{ inputs.java_25 }}" == "true" ]] && VERSIONS+=("25")
          echo "versions=$(printf '%s\n' "${VERSIONS[@]}" | jq -R . | jq -s -c .)" >> $GITHUB_OUTPUT

  build-and-push:
    needs: prepare-matrix
    if: needs.prepare-matrix.outputs.versions != '[]'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    strategy:
      fail-fast: false
      matrix:
        java_version: ${{ fromJSON(needs.prepare-matrix.outputs.versions) }}

    steps:

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
      - name: Setup Taskfile
        uses: ./.github/actions/setup-taskfile
      - name: Resolve and Render
        run: task render

      - name: Set up Docker Buildx
        uses: 
          docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f  # v3
      - name: Login to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9  # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/bake-action@5be5f02ff8819ecd3092ea6b2e6261c31774f2b4  # v6
        id: build
        with:
          source: .
          files: |
            docker-bake.hcl
            versions/${{ matrix.java_version }}/build.hcl
          targets: java${{ matrix.java_version }}
          push: true
      - name: Extract Digests
        id: digests
        run: |
          METADATA='${{ steps.build.outputs.metadata }}'          
          JDK_TARGET="java${{ matrix.java_version }}-jdk_standard"
          JRE_TARGET="java${{ matrix.java_version }}-jre_standard"
          DISTRO_TARGET="java${{ matrix.java_version }}-jre_distroless"
          
          echo "Extracting digest for $JDK_TARGET..."
          JDK_SHA=$(echo "$METADATA" | jq -r --arg t "$JDK_TARGET" '.[$t]["containerimage.digest"]')
          
          echo "Extracting digest for $JRE_TARGET..."
          JRE_SHA=$(echo "$METADATA" | jq -r --arg t "$JRE_TARGET" '.[$t]["containerimage.digest"]')
          
          echo "Extracting digest for $DISTRO_TARGET..."
          DISTRO_SHA=$(echo "$METADATA" | jq -r --arg t "$DISTRO_TARGET" '.[$t]["containerimage.digest"]')          
          echo "Found JDK SHA: $JDK_SHA"
          echo "Found JRE SHA: $JRE_SHA"
          echo "Found Distro SHA: $DISTRO_SHA"          
          echo "jdk=$JDK_SHA" >> $GITHUB_OUTPUT
          echo "jre=$JRE_SHA" >> $GITHUB_OUTPUT
          echo "distro=$DISTRO_SHA" >> $GITHUB_OUTPUT
          task generate-report \
            VERSION=${{ matrix.java_version }} \
            JDK_SHA=$JDK_SHA \
            JRE_SHA=$JRE_SHA \
            DISTRO_SHA=$DISTRO_SHA
      - name: Upload Build Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-report-java-${{ matrix.java_version }}
          path: reports/${{ matrix.java_version }}/main-${{ matrix.java_version }}.json
          retention-days: 1



  scan-images-and-generate-report:
    needs: [build-and-push, prepare-matrix]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
      packages: write

    strategy:
      fail-fast: false
      matrix:
        java_version: ${{ fromJSON(needs.prepare-matrix.outputs.versions) }}
        image_type: [jdk, jre, distroless]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Taskfile
        uses: ./.github/actions/setup-taskfile

      - uses: actions/download-artifact@v4
        with:
          name: build-report-java-${{ matrix.java_version }}
          path: reports/${{ matrix.java_version }}

      - name: get digest
        id: get-digest
        run: |
          echo "digest=$(cat reports/${{ matrix.java_version }}/main-${{ matrix.java_version }}.json | jq -r .digests.${{ matrix.image_type }})" >> $GITHUB_OUTPUT

      - name: login to ghcr
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest ${{ matrix.image_type }} (SLSA)
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32
        with:
          subject-name: ${{ env.ghcr_image }}
          subject-digest: ${{ steps.get-digest.outputs.digest }}
          push-to-registry: true

      - name: Explicit Pull Image
        run: docker pull ghcr.io/${{ github.repository_owner }}/java@${{ steps.get-digest.outputs.digest }}

      - name: Generate SBOM (CycloneDX)
        id: generate_sbom
        uses: anchore/sbom-action@v0.18.0
        with:
          image: ghcr.io/${{ github.repository_owner }}/java@${{ steps.get-digest.outputs.digest }}
          format: cyclonedx-json
          output-file: ${{ matrix.java_version }}-${{ matrix.image_type }}.cyclonedx.json
          upload-artifact: false
          dependency-snapshot: false

      # - name: Upload SBOM to Dependency Graph
      #   run: |
      #     task gh:upload-sbom \
      #       FILE=${{ matrix.java_version }}-${{ matrix.image_type }}.cyclonedx.json \
      #       TARGET=${{ matrix.java_version }}-${{ matrix.image_type }}.sbom \
      #       REPO=${{ github.repository }}
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GITHUB_SHA: ${{ github.sha }}
      #     GITHUB_REF: ${{ github.ref }}

      - name: full-scan-image
        run: |
          task scan-compliance:full-compliance \
            IMAGE=ghcr.io/${{ github.repository_owner }}/java@${{ steps.get-digest.outputs.digest }} \
            REPORT_ID=${{ matrix.java_version }}-${{ matrix.image_type }}-report \
            OS=wolfi \
            IS_DISTROLESS=${{ matrix.image_type == 'distroless' }} \
            OUT_DIR=reports/${{ matrix.java_version }}/${{ matrix.image_type }}

      - name: Upload Scan Report Segment
        uses: actions/upload-artifact@v4
        with:
          name: scan-report-temp-${{ matrix.java_version }}-${{ matrix.image_type }}
          path: reports/${{ matrix.java_version }}/${{ matrix.image_type }}
          retention-days: 1

  merge-and-cleanup-reports:
    needs: scan-images-and-generate-report
    runs-on: ubuntu-latest
    if: always()
    permissions:
      actions: write
      contents: read
    steps:
      - name: Download All Scan Reports
        uses: actions/download-artifact@v4
        with:
          pattern: scan-report-temp-*
          path: final_reports
          merge-multiple: true

      - name: Download All Build Reports
        uses: actions/download-artifact@v4
        with:
          pattern: build-report-java-*
          path: final_reports
          merge-multiple: true

      - name: Delete All Temporary Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: "*"
          failOnError: false

      - name: Upload Final Combined Security Report
        uses: actions/upload-artifact@v4
        with:
          name: final-security-compliance-reports
          path: final_reports
          retention-days: 1

      # - name: Attest JRE (SLSA)
      #   if: steps.digests.outputs.jre != 'null' && steps.digests.outputs.jre != ''
      #   uses:  actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32  # v4
      #   with:
      #     subject-name: ${{ env.ghcr_image }}
      #     subject-digest: ${{ steps.digests.outputs.jre }}
      #     push-to-registry: true

      # - name: Attest Distroless (SLSA)
      #   if: steps.digests.outputs.distro != 'null' && steps.digests.outputs.distro != ''
      #   uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32  # v4
      #   with:
      #     subject-name: ${{ env.ghcr_image }}
      #     subject-digest: ${{ steps.digests.outputs.distro }}
      #     push-to-registry: true