name: Build Java Images

on:
  workflow_dispatch:
    inputs:
      java_8:
        type: boolean
        default: true
      java_11:
        type: boolean
        default: true
      java_17:
        type: boolean
        default: true
      java_21:
        type: boolean
        default: true
      java_25:
        type: boolean
        default: true
      publish:
        type: boolean
        default: true

env:
  DOCKER_IMAGE: docker.io/taha2samy/java

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.set-versions.outputs.versions }}
    steps:
      - id: set-versions
        run: |
          VERSIONS=()
          ${{ github.event.inputs.java_8 }} && VERSIONS+=("8")
          ${{ github.event.inputs.java_11 }} && VERSIONS+=("11")
          ${{ github.event.inputs.java_17 }} && VERSIONS+=("17")
          ${{ github.event.inputs.java_21 }} && VERSIONS+=("21")
          ${{ github.event.inputs.java_25 }} && VERSIONS+=("25")
          JSON_ARRAY=$(printf '%s\n' "${VERSIONS[@]}" | jq -R . | jq -s -c .)
          echo "versions=$JSON_ARRAY" >> $GITHUB_OUTPUT

  build:
    needs: define-matrix
    if: needs.define-matrix.outputs.versions != '[]'
    runs-on: ubuntu-latest
    environment: PUBLISH_IMAGES
    permissions:
      contents: read
      packages: write
      id-token: write 
      attestations: write

    strategy:
      fail-fast: false
      matrix:
        java_version: ${{ fromJSON(needs.define-matrix.outputs.versions) }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lowercase Repository Owner
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event.inputs.publish == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GHCR
        if: github.event.inputs.publish == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_LC }} # استخدمنا الاسم الصغير
          password: ${{ secrets.GITHUB_TOKEN }} 
      
      - name: generate versions
        run: |
          pip install jinja2
          python .github/scripts/render_templates.py

      - name: Docker Bake
        id: bake
        uses: docker/bake-action@v5
        with:
          files: |
            docker-bake.hcl
            versions/${{ matrix.java_version }}/build.hcl
            versions.hcl
          targets: java${{ matrix.java_version }}
          push: ${{ github.event.inputs.publish }}
          set: |
            *.args.GHCR_REGISTRY=ghcr.io/${{ env.OWNER_LC }}

      - name: Extract Digests
        id: digests
        if: github.event.inputs.publish == 'true'
        run: |
          METADATA='${{ steps.bake.outputs.metadata }}'
          echo "jdk=$(echo "$METADATA" | jq -r '."java${{ matrix.java_version }}-jdk-std"["containerimage.digest"]')" >> $GITHUB_OUTPUT
          echo "jre=$(echo "$METADATA" | jq -r '."java${{ matrix.java_version }}-jre-std"["containerimage.digest"]')" >> $GITHUB_OUTPUT
          echo "distro=$(echo "$METADATA" | jq -r '."java${{ matrix.java_version }}-jre-distroless"["containerimage.digest"]')" >> $GITHUB_OUTPUT
      - name: Show Bake Metadata
        run: echo '${{ steps.bake.outputs.metadata }}' | jq .

      # ---------------- JDK ----------------
      - name: Attest JDK (Docker Hub)
        if: github.event.inputs.publish == 'true' && steps.digests.outputs.jdk != 'null'
        uses: actions/attest-build-provenance@v3  
        with:
          subject-name: index.docker.io/taha2samy/java
          subject-digest: ${{ steps.digests.outputs.jdk }}
          push-to-registry: true

      # ---------------- JRE ----------------
      - name: Attest JRE (Docker Hub)
        if: github.event.inputs.publish == 'true' && steps.digests.outputs.jre != 'null'
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: index.docker.io/taha2samy/java
          subject-digest: ${{ steps.digests.outputs.jre }}
          push-to-registry: true

      # ---------------- Distroless ----------------
      - name: Attest Distroless (Docker Hub)
        if: github.event.inputs.publish == 'true' && steps.digests.outputs.distro != 'null'
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: index.docker.io/taha2samy/java
          subject-digest: ${{ steps.digests.outputs.distro }}
          push-to-registry: true

      # ---------------- Verification ----------------
      - name: Verify SLSA 3 Attestation
        if: github.event.inputs.publish == false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🔍 Verifying SLSA Provenance for JDK..."
          if [ "${{ steps.digests.outputs.jdk }}" != "null" ]; then
            gh attestation verify oci://ghcr.io/${{ env.OWNER_LC }}/openjdk@${{ steps.digests.outputs.jdk }} \
              --owner ${{ env.OWNER_LC }}
          fi

          echo "🔍 Verifying SLSA Provenance for JRE..."
          if [ "${{ steps.digests.outputs.jre }}" != "null" ]; then
            gh attestation verify oci://ghcr.io/${{ env.OWNER_LC }}/openjdk@${{ steps.digests.outputs.jre }} \
              --owner ${{ env.OWNER_LC }}
          fi

          echo "🔍 Verifying SLSA Provenance for Distroless..."
          if [ "${{ steps.digests.outputs.distro }}" != "null" ]; then
            gh attestation verify oci://ghcr.io/${{ env.OWNER_LC }}/openjdk@${{ steps.digests.outputs.distro }} \
              --owner ${{ env.OWNER_LC }}
          fi